### ISSUE TITLE
Persist EXIF (specifically GPS) data into output

### ISSUE THREAD

**Issue by techfixpros** [nedhorning/PhotoMonitoringPlugin#6]
When processing images with GPS lat long data, the output image has been stripped of this information. 
It would be helpful for me to have at least this EXIF info saved into the output files, but if possible all of it really should as well.

**Comment by nedhorning** [comment]
The plugin now had the capability of copying the EXIF metadata, including GPS if it is there, from the original photo to the color NDVI or DVI output image.

**Comment by techfixpros** [comment]
Awesome, I will test it out.
